spring:
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_SERVER_HOST:10.1.10.75}:3306/zc_auth_server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: auth-server
  redis:
    host: ${REDIS_HOST:10.1.10.239}
    database: ${REDIS_DATABASE:3}
#logging:
#  level:
#    org.springframework.security: debug
#    org.springframework.security.web: debug