spring:
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_SERVER_HOST:10.1.10.75}:3306/zc_auth_server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: auth-server
  redis:
    host: ${REDIS_HOST:10.1.80.234}
    database: ${REDIS_DATABASE:3}
  wechat:
    trucker:
      app-id: ${TRUCKER_APP_ID:wx3c6860f872cb2cfc}
      app-secret: ${TRUCKER_APP_SECRET:0acd1a92aee027749eff19d953aee562}
  messages:
    basename: classpath:messages
  jackson:
    time-zone: GMT+8
    locale: zh_CN
  auth:
    config:
      default-sms-code: ${DEFAULT_SMS_CODE:123456}
      phone-for-test: ${PHONE_FOR_TEST:13000000000,13000000001,13000000002,13000000003,13000000004,13000000005,13000000006,13000000007,13000000008,17700000000,17700000001,17700000002,17700000003,17700000004,17706420616}
logging:
  level:
    org.springframework.security: info
    com.kybb: info

#    org.springframework.security.web: debug
