version: '3'
services:
  auth-server:
    image: ${DOCKER_REGISTRY}/auth-server:${DOCKER_IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - /home/service/common/common.env
    environment:
      REDIS_DATABASE: 0
      RUN_ARGS: "--server.port=6666"
    container_name: auth-server
    network_mode: host
    volumes:
      - "auth-server:/var/log"
volumes:
  auth-server:
    driver: local